### ISSUE TITLE
Possible to add caps lock as a modifier variant?

### ISSUE THREAD

**Issue by DeeeeLAN** [aru-py/programmer-colemak#8]
I am on linux. I occasionally still want to use caps lock. Is it possible to map it to circle + caps or something so it can still be activated when needed?

**Comment by Nasfame** [comment]
@DeeeeLAN are u interested in working with me on: https://forum.colemak.com/topic/2965-port-qwerty-arabic-to-colemak/

**Comment by aru-py** [comment]
@DeeeeLAN Yes, it should be possible to map a key to `caps lock`. You could use the `◯` key along with any symbol, such as a number.
