### ISSUE TITLE
Port Arabic(Qwerty) to Colemak

### ISSUE THREAD

**Issue by Nasfame** [aru-py/programmer-colemak#9]
Guys is anyone interested to work with me on https://forum.colemak.com/topic/2965-port-qwerty-arabic-to-colemak/

I am Hiro,
discord: laciferin

**Comment by Nasfame** [comment]
@phantomdiorama @aru-py @spicyfalafel @DeeeeLAN

**Comment by aru-py** [comment]
@Nasfame I'd be happy to work with you. Is there anything in particular you need help with?

**Comment by Nasfame** [comment]
@aru-py  Our initial releases  v0.x.x should be targeting macos. Can u review: https://github.com/Nasfame/colemak-arabic/blob/main/execution-plan-macos.md ?

**Comment by Nasfame** [comment]
@aru-py can u review the design plan: https://github.com/Nasfame/colemak-arabic/blob/main/design-plan-v0.x.x.md

I think the execution plan is premature.

**Comment by aru-py** [comment]
@Nasfame Are you looking to migrate just colemak or programmer-colemak?

**Comment by Nasfame** [comment]
@aru-py My current layout is: Colemak
<img width="609" alt="image" src="https://github.com/aru-py/programmer-colemak/assets/24226219/b8b74c71-fa5d-460d-b5c9-60c1db3c29ee">

My personally feel that porting "programmer-colemak" won't be very helpful as most coders primarily code in english.

**Comment by aru-py** [comment]
@Nasfame The layout for programmer-colemak is in the repository. I suggest that you create a regular Colemak layout for Arabic first and then if desired, I can help you create a variation for programmer-colemak.

**Comment by Nasfame** [comment]
What tools do u suggest? Ukelely is ok i guess, karabiner mappings are going to be too slow.

**Comment by aru-py** [comment]
I would recommend Karabiner. I have not found it to be slow in my experience. I am closing this issue for now.

**Comment by Nasfame** [comment]
Well other reason is that the new keymappings will conflict with the existing keymappings and its really not worth it. 56+ keymappings not very cool
